### PR TITLE
WIP - 2015 year in review draft

### PR DESCRIPTION
**Pull request by bzz**
Here is the draft of the blog post "Year in review: Zeppelin project in 2015" with review of the major events in 2015 for Zeppelin project.

TODOs:
 - [ ] add current project status details: N of commiters, etc
 - [ ] add a link to Viewer, with project dashboard
 - [ ] decide where to publish it: blogs.apache.org, blog.nflabs.com or  Medium (or corss-post from above?)
 - [ ] proof-read and spell-check and fix style

### CODE REVIEW

**Comment by bzz** [comment]
\cc @Leemoonsoo  @minahlee @AhyoungRyu for inital review

**Comment by Leemoonsoo** [comment]
Very nice start!

Followings are conferences i have presented Zeppelin

- ApacheCon, Austin
- Hadoop Summit, San jose
- ApacheCon, Budapest
- Flink Forward, Berlin
- Deview, Seoul
- Spark Summit, Amsterdam

Spark summit in California, had a booth.

**Comment by AhyoungRyu** [comment]
@bzz At least to me, It's good draft!

**Comment by bzz** [comment]
@Leemoonsoo have updated conference section and added zeppelin-friends section draft

**Comment by Leemoonsoo** [comment]
Checked updated conference section.

In zeppelin-friends section, 
are 'Engineers from', 'Guys from', 'People from'  temporary name? or ??

**Comment by bzz** [comment]
Good question!
I'd love to have names, but they are scripted and very easy to miss. At the
same time, as I'm talking about ASF where people, not companies participate
and contribute - that's why those references were used.

What do you think?

On Tue, Dec 22, 2015 at 2:25 PM, Lee moon soo <notifications@github.com>
wrote:

> Checked updated conference section.
>
> In zeppelin-friends section,
> are 'Engineers from', 'Guys from', 'People from' temporary name? or ??
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NFLabs/tech-blog/pull/9#issuecomment-166509287>.
>



-- 
--
Kind regards,
Alexander.

**Comment by Leemoonsoo** [comment]
I was thinking names something like 'Zeppelin on the cloud', 'Zeppelin on the product', 'Deep integration'.
But i see what you mean. Just curios how 'engineer', 'guys', 'people' are related to the listed product/service.

**Comment by bzz** [comment]
Have updated the story https://medium.com/@bzz_/apache-zeppelin-incubating-2015-year-in-review-a938d978a309

Merging this in. Will cross-post the updated version to the ASF  blog later

**Pull request merged**
